"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIST_DIR = BASE_DIR.parent.parent / "frontend" / "app" / "dist"

IS_FROZEN = getattr(sys, "frozen", False)

if IS_FROZEN:
    app_data_root = Path(
        os.getenv(
            "LOCALAPPDATA",
            Path.home() / "AppData" / "Local",
        )
    )

    APP_DATA_DIR = app_data_root / "SunriseMailroom"

    APP_DATA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    DATABASE_PATH = APP_DATA_DIR / "db.sqlite3"

else:
    DATABASE_PATH = BASE_DIR / "db.sqlite3"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATABASE_PATH,
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f_&d_s!9ps*(hl&(tru%t3g!f@-f-g!g-rcx@jy09g%#47z(+3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'mailroom',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            FRONTEND_DIST_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Common U.S. timezone overrides:

# ============================================================
# TIMEZONE OVERRIDES
# ============================================================

# Comment out the line below if automatic timezone detection is unavailable.
SUNRISE_LOCAL_TIMEZONE = (os.getenv("SUNRISE_LOCAL_TIMEZONE", "").strip())

# Common U.S. timezones:
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Honolulu"       # Hawaii
# SUNRISE_LOCAL_TIMEZONE = "America/Anchorage"     # Alaska
# SUNRISE_LOCAL_TIMEZONE = "America/Los_Angeles"   # Pacific
# SUNRISE_LOCAL_TIMEZONE = "America/Denver"        # Mountain
# SUNRISE_LOCAL_TIMEZONE = "America/Chicago"       # Central
# SUNRISE_LOCAL_TIMEZONE = "America/New_York"      # Eastern
#
# Uncomment ONE if automatic timezone detection is unavailable.
# UTC-12
# SUNRISE_LOCAL_TIMEZONE = "Etc/GMT+12"
# UTC-11
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Pago_Pago"
# UTC-10 - Hawaii
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Honolulu"
# UTC-9 - Alaska
# SUNRISE_LOCAL_TIMEZONE = "America/Anchorage"
# UTC-8 - Pacific
# SUNRISE_LOCAL_TIMEZONE = "America/Los_Angeles"
# UTC-7 - Mountain
# SUNRISE_LOCAL_TIMEZONE = "America/Denver"
# UTC-6 - Central
# SUNRISE_LOCAL_TIMEZONE = "America/Chicago"
# UTC-5 - Eastern
# SUNRISE_LOCAL_TIMEZONE = "America/New_York"
# UTC-4 - Atlantic
# SUNRISE_LOCAL_TIMEZONE = "America/Halifax"
# UTC-3
# SUNRISE_LOCAL_TIMEZONE = "America/Argentina/Buenos_Aires"
# UTC-2
# SUNRISE_LOCAL_TIMEZONE = "America/Noronha"
# UTC-1
# SUNRISE_LOCAL_TIMEZONE = "Atlantic/Azores"
# UTC+0
# SUNRISE_LOCAL_TIMEZONE = "Etc/UTC"
# UTC+1 - Central European
# SUNRISE_LOCAL_TIMEZONE = "Europe/Paris"
# UTC+2 - Eastern European
# SUNRISE_LOCAL_TIMEZONE = "Europe/Athens"
# UTC+3
# SUNRISE_LOCAL_TIMEZONE = "Europe/Moscow"
# UTC+4
# SUNRISE_LOCAL_TIMEZONE = "Asia/Dubai"
# UTC+5
# SUNRISE_LOCAL_TIMEZONE = "Asia/Karachi"
# UTC+6
# SUNRISE_LOCAL_TIMEZONE = "Asia/Dhaka"
# UTC+7
# SUNRISE_LOCAL_TIMEZONE = "Asia/Bangkok"
# UTC+8
# SUNRISE_LOCAL_TIMEZONE = "Asia/Singapore"
# UTC+9
# SUNRISE_LOCAL_TIMEZONE = "Asia/Tokyo"
# UTC+10
# SUNRISE_LOCAL_TIMEZONE = "Australia/Brisbane"
# UTC+11
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Guadalcanal"
# UTC+12
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Auckland"
# UTC+13
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Apia"
# UTC+14
# SUNRISE_LOCAL_TIMEZONE = "Pacific/Kiritimati"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    FRONTEND_DIST_DIR / "assets",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
